### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/NHSRplotthedots#123]
The repository doesn't have a code of conduct for contributions: https://www.contributor-covenant.org/version/2/1/code_of_conduct/

**Comment by tomjemmett** [comment]
can we just use what you have added to the [template](https://github.com/nhs-r-community/template) for this?

**Comment by Lextuga007** [comment]
Yes, that'll be the one to use.

**Comment by Lextuga007** [comment]
@tomjemmett  Do CRAN package repositories require the Code of Conduct to be included or could this be linked to the assets repository like the logo is?
