### ISSUE TITLE
Plotly implementation

### ISSUE THREAD

**Issue by ChrisBeeley** [nhs-r-community/NHSRplotthedots#126]
Maybe with help from @AYu1804 ?

**Comment by tomjemmett** [comment]
for the most part, using something like this will work:

``` r
data |>
  ptd_spc(values, dates) |>
  plot() |>
  ggplotly()
```

presently there is a slight issue with using ggplotly though - we have a custom Geom (GeomPTDIcon) which plotly doesn't know about. We need to build an implementation of `geom2trace` for this (`geom2trace.GeomPTDIcon()`).

**Comment by tomjemmett** [comment]
the most dumb implementation of `geom2trace.GeomPTDIcon()` is:

``` r
geom2trace.GeomPTDIcon <- function(data, params, p) NULL
```

this will just stop the warning message "`geom_GeomPTDIcon() has yet to be implemented in plotly`".

A better approach may be to implement something like the following, where we display a warning once per session

``` r
geom2trace.GeomPTDIcon <- function(data, params, p) {
  if (!getOption("ptd_disable_plotly_geomptdicon_warning", FALSE)) {
    options("ptd_disable_plotly_geomptdicon_warning" = TRUE)
    warning(
      "This package does not yet support showing the 'Plot the dots' icons in plotly.\n",
      "This warning is shown once per R session. You can permanently disable this warning by adding ",
      "options(\"ptd_disable_plotly_geomptdicon_warning\" = TRUE) ",
      "to your .Rprofile"
    )
  }
  NULL
}
```
