### ISSUE TITLE
Crosstalk with SPC Chart Functionality

### ISSUE THREAD

**Issue by HanselPalencia** [nhs-r-community/NHSRplotthedots#128]
I'm attempting to implement a crosstalk filter on an spc chart, however, I am facing the error:

`Error: ptd_spc: .data must be a data.frame`

Reading the ?help file it states that the end value of the `ptd_spc()` function is **"A ggplot2 object of the spc charts."**
I'm relatively certain it most likely has something to do with some error handling in the beginning of the data manipulation?

`
assertthat::assert_that(
    inherits(.data, "data.frame"),
    msg = "ptd_spc: .data must be a data.frame"
  )`

I'm not sure if it would be possible to fix this so that we could include SharedData classes, but just a thought that I feel would be useful to a lot of people who might not have shiny support in their orgs.

**Comment by tomjemmett** [comment]
the documentation is wrong (I've created #129 for that). But, that error message is because the data passed to `ptd_spc` must inherit from "data.frame" (so, tibbles/data.tables should be fine).

if you can, could you provide a [reprex](https://github.com/tidyverse/reprex) and I can have a look into this? I'm not massively familiar with crosstalk unfortunately, but my guess is the initial data isn't correct.

**Comment by HanselPalencia** [comment]
The code below will generate two working graphs with crosstalk capabilities (i.e. filtering a single dot on a plotly graph will filter the other graph as well)

With that, if we attempt to throw `shared_dat` into the `ptd_spc()` function we will get the error mentioned in the opening post.

Throw all of this code into a code chunk in a .Rmd file to see how it works as I was too lazy to implement some sort of `par(mfrow)` functionality to see two plots side by side.

```{r}

# Generating Random Data
dates <- seq(as.Date("2000/1/1"), by = "month", length.out = 36)
vals <- rnorm(36)
dat <- data.frame(dates = dates, values = vals)



library(NHSRplotthedots)
library(plotly)

ptd_spc(dat, date_field = dates, value_field = values) %>% 
  ptd_create_ggplot() %>% 
  ggplotly() %>% 
  layout(legend = list(orientation = "h",
                       xanchor = 'center',
                       x = .5,
                       y = -.4))



library(crosstalk)


## Crosstalk uses these shared dataset classes (R6) to communicate between viz

shared_dat <- SharedData$new(dat)

p1 <- shared_dat %>% 
  ggplot() +
  geom_point(aes(x = dates, y = values))

ggplotly(p1)


p2 <- shared_dat %>% 
  ggplot() +
  geom_point(aes(x = dates, y = values))

ggplotly(p2)


# ptd_spc(shared_dat) THROWS ERROR



```

**Comment by tomjemmett** [comment]
so I think the issue is that in this example, strictly the data is not shared between the two plots: in order to run create a plot the dot's plot we need to run it through `ptd_spc()` which modifies the data.

there are a couple of approaches to take here, one would be to do something like take our original data, run it through the spc function, then join the spc data back to the original data. This would mean you need to completely reconstruct the plot though

``` r
library(NHSRplotthedots)
library(NHSRdatasets)
library(plotly)
library(tidyverse)
library(crosstalk)

ae_attendances_subset <- ae_attendances |>
  filter(org_code == "RL4")

spc <- ae_attendances_subset |>
  ptd_spc(breaches, period, facet_field = type) |>
  as_tibble()

spc

dat <- ae_attendances_subset %>%
  mutate(across(period, as.POSIXct)) |>
  inner_join(spc, by = c("period" = "x", "breaches" = "y", "type" = "f"))

shared_dat <- SharedData$new(dat)

p1 <- shared_dat %>%
  (\(.x) ggplot(.x) +
     geom_point(aes(x = period, y = 1 - breaches / attendances))
  )() %>%
  ggplotly()

p2 <- shared_dat %>%
  (\(.x) ggplot(.x, aes(x = period, y = breaches)) +
     geom_point() +
     geom_line(aes(y = mean)) +
     geom_line(aes(y = lpl)) +
     geom_line(aes(y = upl))
  )() %>%
  ggplotly()

subplot(p1, p2, nrows = 1, widths = c(0.3, 0.7), titleX = TRUE) %>%
  hide_legend() %>%
  animation_opts(1000, redraw = FALSE) %>%
  layout(hovermode = "n", margin = list(l = 100)) %>%
  highlight(
    "plotly_selected", 
    color = "red", 
    opacityDim = 1, 
    hoverinfo = "none"
  )
```

I'll continue reading the doc's and try to get a better idea of how crosstalk works

**Comment by tomjemmett** [comment]
this may require turning `ptd_spc()` into a generic, with two implementations (`ptd_spc.data.frame()` and `ptd_spc.SharedData()`). Testing shows that this does sort of get crosstalk to work, but may need tweaking (it does things like not only highlighting the points but also colouring in the mean line)

**Comment by tomjemmett** [comment]
[working branch](https://github.com/nhs-r-community/NHSRplotthedots/tree/support_crosstalk_SharedData)
