### ISSUE TITLE
Time series validation - check for duplicates

### ISSUE THREAD

**Issue by chrisreading01** [nhs-r-community/NHSRplotthedots#13]
Something that cropped up while testing one of my datasets - should there be an extra validation step to make sure that the data frame provided to the function doesn't contain more than one value per time index? And return an error message if there is more than one value?

Similarly, although more complicated, what about checking for completeness, if there are missing data points. Although for this I think the user would need to supply some kind of value like "Weekly"/"Monthly"/"2 weekly" to the function so it would have something to base the required frequency of values on.

Thoughts?

**Comment by ThomUK** [comment]
I think both might be possible without needing input from the user.  

The check for duplicates could compare `length(all_dates) `with the value of `length(unique(all_dates))`.  
The check for completeness could check that difference between adjacent dates (using `lead()` or `lag()`) is the same for all.  

It might be a new test, or just a couple of new assertions if there's already a test for the date field.

**Comment by tomjemmett** [comment]
one way would be to `count()` with the dateField and facetField, then seeing if `any(count$n > 1)`.

**Comment by tomjemmett** [comment]
I've made an implementation of this in #48 https://github.com/nhs-r-community/NHSRplotthedots/blob/c54be4b545591687bae79d8f2873a4b65fbc2d9d/R/spcOptions.R#L113
