### ISSUE TITLE
Accessibility - change "here" to more descriptive link

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/NHSRplotthedots#144]
Following the thread https://twitter.com/Em1lySm/status/1516741011422199810 it's advisable to not just use "here" as a link for accessibility.

https://github.com/nhs-r-community/NHSRplotthedots/blob/5a4af03caff10a7ea6b8027ca72feae4b1003584/README.md
https://github.com/nhs-r-community/NHSRplotthedots/blob/ca67eae34ae3aa228415d6ba0ef861da272cf840/vignettes/intro.Rmd - this says [mdc] but preferably should be written out in full to Making Data Count as mdc is not a recognised universal acronym (yet!).

**Comment by tomjemmett** [comment]
I would suggest those instances are converted to

````
['Making Data Count' programme][mdc].
```

**Comment by tomjemmett** [comment]
@Lextuga007 - can this be closed?

**Comment by Lextuga007** [comment]
Looks like we still have a "Please see here" https://github.com/nhs-r-community/NHSRplotthedots/blob/bcf5f8cdb9fc74f3c2b30fb489973fce1fa58e71/vignettes/intro.Rmd#L17 so I'll fix that before closing.

**Comment by tomjemmett** [comment]
oh, before changing that, wait for #176 to merge

**Comment by tomjemmett** [comment]
or, at least start your PR off of #176 to begin with. Otherwise, you are going to be in merge conflict hell :-)
