### ISSUE TITLE
Need ability to fix baseline period for SPC calculations

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#16]
The current plot the dots tool has a facility to fix the baseline period to between 12 and 20 "units" (days, weeks, months).  This fixes the periods over which the SPC calculations are run, and prevents the tool from losing sensitivity as more data is added (through the limits widening).  

The screenshots below show it's effect in the excel tool (same data in each plot).  

Baseline set to 20 months.  SPC calcs are done on the first 20 months.  Points 13, 14, and 19 push the control limits wider, and the last points are not highlighted as unusual.  
![image](https://user-images.githubusercontent.com/10871342/124133090-62e4ec80-da79-11eb-8887-52778daef93d.png)

Baseline set at 12 months.  The SPC calculations are done on the first 12 months.  The limits remain narrow, and the final points are highlighted as unusual.  
![image](https://user-images.githubusercontent.com/10871342/124133054-5b254800-da79-11eb-9b59-dbfc807b1c47.png)

**Comment by chrisreading01** [comment]
This should be an easy amendment. I would suggest that it's an either/or argument for the function paired with the rebase argument. It would conflict if a user tried to rebase at specified intervals but also freeze after N points. Something in the validation of parameters section needed to return a warning if you try to use both?

**Comment by ThomUK** [comment]
Would it be feasible for them both to work together?  So a rebase point would begin a new set of calculations, which would update up to the baseline number, and freeze after that (or until another rebase).  I think that's how the excel tool works (but we could store a list of these questions for the next time we meet the plot the dots team).
