### ISSUE TITLE
Add helper diagrams to the repo

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#162]
Tom Hook on Slack created some helper diagrams which are often needed by people writing reports using this package. 

Suggest we add these to a repo in case they're useful for others. Screenshot below but I'll move the files over to this issue when I'm back at a pc.

![Screenshot_20220930-142643.jpg](https://user-images.githubusercontent.com/10871342/193280380-2b5d1f57-0aa2-4a05-896b-775183caf4ad.jpg)

**Comment by tomjemmett** [comment]
I have been working on the icons to use the icons used in the excel tool (see [update_icons](https://github.com/nhs-r-ommunity/NHSRplotthedots/tree/update_icons) branch), but haven't got round to finishing it off. From memory the main thing is to replace the icons with higher quality png's or svg's (latter ideally), but need to get them from the PTD team.

**Comment by ChrisBeeley** [comment]
Is this issue ready to be closed?
