### ISSUE TITLE
Does not flag a decreasing trend of seven

### ISSUE THREAD

**Issue by tomjemmett** [nhs-r-community/NHSRplotthedots#167]
If there is a trend of 7 points increasing in a row, these are all correctly classed as special cause

``` r
library(NHSRplotthedots)

data.frame(x = Sys.Date() + 0:7, y = 0:7) |> ptd_spc(y, x)
#> Warning in ptd_add_short_group_warnings(.): Some groups have 'n < 12'
#> observations. These have trial limits, which will be revised with each
#> additional observation until 'n = fix_after_n_points' has been reached.
```

![](https://i.imgur.com/zmvLDUY.png)

However, if the trend is decreasing, the points aren't flagged as special cause

``` r

data.frame(x = Sys.Date() + 0:7, y = 0:-7) |> ptd_spc(y, x)
#> Warning in ptd_add_short_group_warnings(.): Some groups have 'n < 12'
#> observations. These have trial limits, which will be revised with each
#> additional observation until 'n = fix_after_n_points' has been reached.
```

![](https://i.imgur.com/erDl8i2.png)

The issue is with [`ptd_part_of_seven_trend()`](https://github.com/nhs-r-community/NHSRplotthedots/blob/861300920fe22feaef08c569bb8903d37464c393/R/ptd_calculate_point_type.R#L43) - we pass in a vector of either 0's, 1's, or -1's, but we only check if the value is 1. We need to take the absolute value of the vector

**Comment by ThomUK** [comment]
Good spot, Tom
