### ISSUE TITLE
Y axis format (e.g. time MM:SS)

### ISSUE THREAD

**Issue by las-luke-rogerson** [nhs-r-community/NHSRplotthedots#174]
This may be quite straightforward as is, but would appreciate some pointers.

It would be useful to include a parameter into the ptd_create_ggplot() function which allows the y axis format to be specified. In our tests of the package we are often looking at improvement in waiting times, where reporting in either minutes-seconds or hours-minutes is desirable. Decimal minutes is straightforward but rarely translates well to a non-statistical audience.

**Comment by tomjemmett** [comment]
the object returned by `ptd_create_ggplot` is just a ggplot object, so you can always do something like

``` r
ptd_create_ggplot(spc) +
  scale_y_continuous(...)
```

it may give a warning about replacing an existing axis, but that's fine to ignore.

adding too many arguments to the plot function will make it confusing, so I would favour utilising standard ggplot stuff where possible

**Comment by las-luke-rogerson** [comment]
Thanks Tom, I'll test that.
