### ISSUE TITLE
Document the use of the summary function in readme/intro vignette

### ISSUE THREAD

**Issue by tomjemmett** [nhs-r-community/NHSRplotthedots#184]
The solution for #164 already exists in the form of the `summary()` method. However, this method is not mentioned in the Readme or intro vignette.

We could do with a paragraph in both of these showing how you can use `summary` to get some basic statistics about your spc data frame, and how this could be used (`summary()` prints the spc options, and then returns the summarised results. The main usage of `summary()` is in an interactive case, so this summarised table is typically also printed, but you could assign this table to a variable and use it later).

**Comment by marcosfabietti** [comment]
https://github.com/nhs-r-community/NHSRplotthedots/pull/198

created pull request for it, please review
