### ISSUE TITLE
Add integration with e.g. PowerBI to documentation

### ISSUE THREAD

**Issue by ChrisBeeley** [nhs-r-community/NHSRplotthedots#186]
Every 3 months someone on Slack asks about using this package with PowerBI. It would be useful to add guidance on this to the docs

**Comment by ThomUK** [comment]
If anyone is using this package together with powerBI, please get in touch so that we can do this...

**Comment by tomjemmett** [comment]
I think the tl;dr is this isn't possible. There was a good talk at the NHS-R virtual conference about getting it to work, but I feel it's really outside the scope of handling within this package.

One thing that might be worth implementing is a much simpler abstraction of the logic for modifying the data; that could then just be copied manually into a PowerBI R script and used. It would need to be base R to require no dependencies, and then it would be up to the user to create the chart.

Closing for now, but happy to have it re-opened at some point if things change with the Power BI service

**Comment by ChrisBeeley** [comment]
Could we instead document that it isn't possible and give some pointers in the docs?
