### ISSUE TITLE
Update documentation to illustrate use of the new label_limits option

### ISSUE THREAD

**Issue by francisbarton** [nhs-r-community/NHSRplotthedots#192]
Happy to have this assigned to me.

- [x] Update README to add 1 example with secondary axis labels
- [-] Update vignette(s)?

edit: I decided a whole vignette was a bit OTT for this. Just added example to README.

**Comment by ThomUK** [comment]
Fran, as part of this PR, you could add yourself as a package author to the DESCRIPTION too...

**Comment by francisbarton** [comment]
Oh good point, will do 😎

**Comment by francisbarton** [comment]
Closed by #214
