### ISSUE TITLE
Inconsistent colours between special/common cause plotting & icons

### ISSUE THREAD

**Issue by andrjohns** [nhs-r-community/NHSRplotthedots#196]
Hi All! When using the default colours & icons for special/common cause highlighting in the [PowerBI visual](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC) we've noticed some (very) small inconsistencies in the colour values:

Type | [ptd_spc_colour](https://github.com/nhs-r-community/NHSRplotthedots/blob/main/R/ptd_spc_colours.R#L16) | [icon](https://github.com/nhs-r-community/NHSRplotthedots/tree/main/inst/icons/variation)
-- | -- | --
common_cause | #7b7d7d | #BFBFBF
special_cause_improvement | #289de0 | #0072C6
special_cause_neutral | #361475 | #8000C0
special_cause_concern | #fab428 | #FF6600

Also as an FYI, it looks like the colours in the excel SPC template (from future NHS) very slightly differ from these as well. 

Is there a reference document/spec for the exact colour values to use here? Possibly a little pedantic, but always good to be careful!

**Comment by ThomUK** [comment]
Hi @andrjohns, thanks for raising this - not pedantic at all.  Projects have been forked over smaller annoyances than this!  Do you have a screenshot of the difference that we could use to bring the problem to life for people?

NHSRplotthedots aims to follow the NHS England tools as closely as possible.  @MatthewCallus do you have a set of colour codes you would prefer us to move towards for consistency?  Shall we standardise on the current icon colours?

**Comment by MatthewCallus** [comment]
Thanks, @ThomUK, for adding me.

I have discussed this with the team. We currently use different colours in different tools, and I believe the colours for the icons are different too. We will look to standardise these, as well as make any necessary changes to increase accessibility (adding purple to the mix has made this a bit harder). I'll make a note to come back with an update.

@andrjohns, if you want the colours currently in use, I'm happy to share, but hopefully we'll be in a position to update these in the next week or so.

**Comment by andrjohns** [comment]
Thanks for the clarification, much appreciated!

@pli9 FYI on the updated colour codes

**Comment by ThomUK** [comment]
Thanks @MatthewCallus.
@tomjemmett would you mind re-opening this issue - we should implement the standard colours here.

Comparison below (the white dot is the new standard colour)

![Screenshot_20231207-061658.png](https://github.com/nhs-r-community/NHSRplotthedots/assets/10871342/486c4ab5-7d4d-4893-9a51-1c1dc6d501b9)

**Comment by marcosfabietti** [comment]
https://github.com/nhs-r-community/NHSRplotthedots/pull/199 pull request for this

**Comment by ThomUK** [comment]
This was closed by #199, @tomjemmett would you be able to close this issue?
