### ISSUE TITLE
Refactoring main function into individual functions

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#2]
As Chris Reading proposed, this issue covers refactoring the main spc function into smaller individual functions.  I propose:

* Function for data validation / parameter validation - sub-issue #3
* Function to do basic SPC calculations - sub-issue #6 
* Function to do calculations related to the particular point highlighting ruleset (eg NHSEI ruleset, Shewhart ruleset, Western Electric ruleset) - sub-issue #7 
* Function to handle the ggplotting - sub-issue #4
* Function to handle ggplot theming (allowing theme customisations later) - ~~sub-issue #4~~ - sub-issue #8 

I'm fairly new to collaborating through github, so let me know if these should be split up into separate issues.  Thank you!

**Comment by ChrisBeeley** [comment]
This is great, thanks for getting the ball rolling. I think one big issue with the overall structure in is good, and then ideally file separate issues for the individual bits before you tackle them. This will allow others to discuss them, as well as making sure that two people are not working on the same issue at the same time

**Comment by Lextuga007** [comment]
Agreed, this is a great start Thom and we are definitely learning more about Git collaboration as we work on this! As @ChrisBeeley suggests each one of these is valid as an issue and you've raised a few already. I'm going through and labelling but not assigning - please take any that you are working on. Not all the points have issues though - could you add these before I close this as an overall issue?

Also, @SimonW-M is arranging a meeting next week to discuss this project.

**Comment by ThomUK** [comment]
Hi @Lextuga007, thanks, I've added the issues and references now.  I'm not sure how to self-assign work?  I'm not sure I have that permission.

**Comment by ThomUK** [comment]
All but one of these original sub-issues are closed now, so I'm closing this one.  #8 is the final issue to complete (assigned to me and nearly finished).
