### ISSUE TITLE
Multiple gridlines overlapping

### ISSUE THREAD

**Issue by chrismainey** [nhs-r-community/NHSRplotthedots#25]
When writing this plot for the vignette, it looks like I'm getting multiple gridlines on the yellow points.
Haven't had time to investigate, just filing it for now.

```
library(NHSRdatasets)
library(tidyverse)

data("ae_attendances")
stable_set <- 
  ae_attendances %>% 
  filter(org_code == 'RRK' & type ==1 & period < as.Date('2018-04-01'))

spc(stable_set, valueField = breaches, dateField = period)
```

**Comment by ThomUK** [comment]
I can reproduce that, but I've never seen it before.  Checking the 2nd pic it seems to somehow be moving the gridlines from before and after the x axis labels.  
![plot from main branch](https://user-images.githubusercontent.com/10871342/126222575-6aabcdae-3a36-4da2-926a-fdfc50b5159e.png)

It doesn't appear in the development branch (though the call to spc() will need to pass the column names as strings).  
```
devtools::install_github("nhs-r-community/NHSRplotthedots@development", force = TRUE)

spc(stable_set, valueField = "breaches", dateField = "period")
```
![plot from development branch](https://user-images.githubusercontent.com/10871342/126224295-f27cf776-871c-4faf-ad9f-8b7ccd25aaeb.png)

**Comment by chrismainey** [comment]
Good spot.  I've switched over to the development branch now, so happy that it's not overlapping.  Closed.
