### ISSUE TITLE
Default values in SPCOptions

### ISSUE THREAD

**Issue by chrismainey** [nhs-r-community/NHSRplotthedots#26]
Can we add the default values that the spcOptions function uses into the help file?  I haven't investigated yet, but improvement direction, for example, is presumably got a default value?  This may be in the code, but is probably best handled as a default value in the function call which can then be documented in the help.

**Comment by ThomUK** [comment]
Yes, there are some defaults set near the top of the spc() function.  
The ones that would interest someone using the function for the first time are:
- improvementDirection (default = increase)
- mainTitle (default = "SPC Chart")
- xAxisLabel (default = "Date")
- yAxisLabel (default = "Value")

The rest of the options relate to axis breaks, label formatting, percentages, and axis treatment during facet plotting.

I need to own up to not keeping spcOptions() up to date through the changes I've done on the development branch, so I don't think it's working on that branch.  Now that the validateParameters() function exists at the top of spc(), I was working on the assumption that we would remove the spcOptions() function and create the list directly like:
```
spc(dataFrame, valueField = "values", dateField = "dates", options = list(rebase = "rebaseColumnName"))
```

Thinking about in in the context of defaults though, it would be easier to document defaults if the spcOptions() function remained.

**Comment by chrismainey** [comment]
Yes, I agree it would be easier to document the spcOptions function.  My preference would be to retain, it but what do you think @ThomUK @chrisreading01 ?

**Comment by ThomUK** [comment]
Yes, on balance I think it's better to keep spcOptions().  Now that we have validation happening in the main spc() function though, I would propose moving all the validation there to avoid duplicating it, and to protect the spc() function from people (like me :-~ ) who pass a list in directly.  In that case spcOptions() would become a simple pass-through to create a list with the right variable names, and also a place to document the defaults for users.  

What do you think @chrismainey @chrisreading01 ?

**Comment by chrismainey** [comment]
I think that makes sense.  Validate all inputs in spc (or fire them out to validate function), then spcOptions is just an empty list with names slots, useful for the documentation, exactly as you've said @ThomUK.

**Comment by tomjemmett** [comment]
I have a feeling some of this, if not all, will be covered in #48

**Comment by tomjemmett** [comment]
as #48 is merged, @ThomUK would you mind reviewing the default options in createGgplot() and updating as necessary? Ta!

**Comment by tomjemmett** [comment]
documenting here current defaults:

ptd_spc:
- improvement_direction = "increase"

ptc_create_ggplot:
- point_size = 4
- percentage_y_axis = FALSE
- main_title = NULL (calculated)
- x_axis_label = NULL (calculated)
- y_axis_label = NULL (calculated)
- fixed_x_axis_multiple = TRUE
- fixed_y_axis_multiple = TRUE
- x_axis_date_format = "%d/%m/%y"
- x_axis_breaks = NULL (calculated)
- y_axis_breaks = NULL (calculated)
- colours = ptd_spc_colours()

the only consideration here I have had is to create a ptd_spc_theme() which could replace the theme_override argument
