### ISSUE TITLE
Add error handling for the plots

### ISSUE THREAD

**Issue by chrismainey** [nhs-r-community/NHSRplotthedots#28]
Truncation occurs on some of the geom_point arguments, presumably because of scaling.  These could be caught and handled, or set to the same length as the scaling.  It might confuse the user and make them think they've done something wrong.

**Comment by ThomUK** [comment]
Hi @chrismainey, would you say this is the same error as #17 ?

**Comment by chrismainey** [comment]
Yes, same as 17. So I'll close this one.  Had similar in my FunnelPlotR package, and it was because the control limits were longer than the plot which screwed scaling up
