### ISSUE TITLE
Alter handling of the no facet detected message.

### ISSUE THREAD

**Issue by chrismainey** [nhs-r-community/NHSRplotthedots#29]
No facet detected - binding pseudo-facet column.
This might be better to set it to a default value of 1 or something that is silently handled, rather than raising the error message that comes out in the output.

**Comment by ThomUK** [comment]
This is fixed in the development branch (commit 38eda51d55233883cff9c9f70de04b0a16060f13).  
Shall we move the development branch into main, or would it be worth writing the vignettes based on the development version until we make the first development release?

**Comment by chrismainey** [comment]
If you are happy with the development branch, it would be good to move it into the main branch before it is presented next week.  Ideally soon, and I'll adjust vignette for it.  Is the development branch in the main repo, or do you mean your fork?

**Comment by ThomUK** [comment]
@chrismainey Development branch in the main repo should be fine.  Some description changes, and fancy github hooks have been committed to master branch, but other than that all the work so far has happened in development.

**Comment by chrismainey** [comment]
I've moved my vignette to development branch now and it is fixed.
