### ISSUE TITLE
Refactoring data and parameter validation from main spc() function

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#3]
This is a sub-issue to overall issue - #2 
I propose refactoring the data and parameter validation code into a self-contained function.  

The new function will check data types, values, and missing data in the dataframe, and should stop execution with a helpful error message if it finds a problem.  

There is currently some code that assigns data to internal variables within the validation code.  I propose keeping that separate from the new validation function.  It could be refactored separately into a calculation step (or be included in the main SPC calculation function).

**Comment by Lextuga007** [comment]
Just checking with @tomjemmett on this as he has previously looked into data formatting. There was a lot involved in it I gathered but it sounded like a really good foundation to work from. It will be good to get Tom's view on this.

**Comment by ThomUK** [comment]
Hi, I've done some work on this in my local repository too.  Be great to compare notes with Tom.

**Comment by ThomUK** [comment]
Hey @tomjemmett, I have some code written for this locally.  It tests that errors are thrown for various invalid input types.  I'll clean it up and push it to my github account soon so I can link to it here.  I'd really value your opinion on whether there's a better (shorter?) way.

**Comment by tomjemmett** [comment]
Thanks @ThomUK , if you want to tag me as a reviewer on the PR or email me when it’s pushed to your repo will review! 👍
