### ISSUE TITLE
Take default x and y axis names from dataframe columns

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#31]
At the moment, the defaults are hard-coded as "Date", and "Value".  

Taking the defaults from the dataframe column names seems sensible.  It would also give two ways for a user to change the labels, either through the spc() options, or by renaming column names in the dataframe with dplyr::mutate().

**Comment by chrisreading01** [comment]
I second this :) I'll take a look at the PR this evening and try and merge it along with the ggplot subfunction.
