### ISSUE TITLE
resolve lintr warnings

### ISSUE THREAD

**Issue by tomjemmett** [nhs-r-community/NHSRplotthedots#38]
lintr is giving a number of style warnings - once we have merged existing PR's we could consider sorting these issues.

However, as this will affect pretty much every .R file it may be worth having a bit of a cease-fire on development, sorting the lint issues, then everyone making sure they have an up to date copy of the repo.

**Comment by ThomUK** [comment]
This sounds a good idea. I have quite a big chunk of work on my repo relating visual appearance of the plot. I can't remember how many files it touches, but I'd like to merge it before we do the lint fixing if possible.  I just have the grid/ggplot/test problems to fix.

The branch in question is the  one on my repo starting 8_
