### ISSUE TITLE
Rename data.frame argument

### ISSUE THREAD

**Issue by chrismainey** [nhs-r-community/NHSRplotthedots#39]
Can we rename the data.frame argument in the `spc` and `spcStandard` functions, because the conflicts with the base function data.frame and gets in the way of debugging too.  I propose `dataset`, which is then described as a data.frame in the help file.

**Comment by tomjemmett** [comment]
another option may be to use the tidyverse approach of avoiding conflicts, e.g. call the argument .data.

**Comment by chrismainey** [comment]
Happy with either option.  @chrisreading01 , what would you prefer?

**Comment by chrisreading01** [comment]
I think going with dataset probably causes the least confusion. Should be a straightforward swap, hopefully!

**Comment by tomjemmett** [comment]
straightforward swap. Though, there is a bit of a name collision with dataset (base has the datasets package!). I would say as all the tidyverse functions (that I know of anyway) use .data as their first argument then it would be less confusing to be a sheep and go with the crowd! :-)

**Comment by chrisreading01** [comment]
I've got no real problem with .data, other than object names with a dot in front of them somehow look weird to my eyes! I'll go with the majority :)

**Comment by chrismainey** [comment]
Cool.  Let's go with .data then.  I'm happy to do this one, as I already tried it with my fork. Happy for me to PR, or have you already done it in refactor @tomjemmett ?

**Comment by tomjemmett** [comment]
I'll solve with my refactoring - it was something lintr picked up anyway!

**Comment by chrismainey** [comment]
Ah, ok.  I've done it now though.  Want me to PR anyway or leave it?

**Comment by tomjemmett** [comment]
#43 will close this - I've renamed to .data. There is a slight conflict here, in rlang::.data - however, this variable is provided for convenience of getting around rcmd check warnings, and will just be the same data frame as we are passing into each function anyway.
