### ISSUE TITLE
Refactoring ggplot2 and ggplot theme functions from main spc() function

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#4]
This is a sub-issue to overall issue - #2 
I propose refactoring the ggplot2 ~~and ggplot theme~~ code into self-contained function~~s~~ within the main spc() function.  

The new function~~s~~ will be responsible for:
* ~~Theme function - returning a default NHSEI theme (could be extended with additonal themes later) to pass into the new ggplot2 function.~~ - work on theme moved to separate issue #8 
* ggplot2 function - returning the plot object, and keeping all the implementation detail out of the main spc() function.  

Let me know if anyone has any thoughts on any of the above.  Thank you!

**Comment by Lextuga007** [comment]
Just going through the issues and I was just wondering if the struck through points were part of a checklist? If it is this might be really useful: https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/about-task-lists as you can put a checklist in an issue  :smile:
