### ISSUE TITLE
unused code

### ISSUE THREAD

**Issue by tomjemmett** [nhs-r-community/NHSRplotthedots#44]
https://github.com/nhs-r-community/NHSRplotthedots/blob/eb22de353f2ac4abe4db3a56d247ad3d084334ac/R/spcStandard.r#L34 has code that `{lintr}` has determined to not be used. Is this meant to be used somewhere, but isn't? Or, can it be deleted?

**Comment by tomjemmett** [comment]
I think I've determined that this is deleteable code, at least I have in #48 and haven't had any issues! If we decide to merge #48 then that will resolve this

**Comment by ThomUK** [comment]
Yes, Chris also removed in #52

**Comment by chrisreading01** [comment]
Yes this can go, I think it just got copied across in error when the function was split up into subfunctions :D
