### ISSUE TITLE
Placeholder for purple dots ("neutral" improvement direction)

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#54]
The excel tool will soon support metrics where the improvement direction is "neutral", and the current "concern" and "improvement" dot colours could cause confusion.  eg. measures on activity levels where increases and decreases need monitoring, but do not have a strong link to either positive or negative change.

Proposal is to adopt a purple dot colour, which would replace both blue and orange dots, to signal special causes happening on either side of the mean.

We need to wait until the updated excel tool is released to implement this, but this issue is to flag as something to keep in mind.

**Comment by tomjemmett** [comment]
I think this should be relatively straight forward to implement, assuming we go with improve_direction = "neutral", which we convert to 0 for `ptd_calculate_point_type()`:

``` r
    point_type = case_when(
        !special_cause_flag ~ "common_cause",
        improvementDirection == 0 ~ "special_cause_neutral",
        relative_to_mean == improvement_direction ~ "special_cause_improvement",
        TRUE ~ "special_cause_concern"
      )
```

we would then just need to add a line into `ptd_colours()`:

``` r
special_cause_neutral = "some_colour"
```
