### ISSUE TITLE
provide a way to influence the aspect-ratio of the plot output

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#59]
The plot output from R is typically a different aspect-ratio that the plot output by the excel #plotthedots tool.  For many users this will not matter, but for those looking to move from existing reports generated by excel, to automated output generated with NHSRplotthedots, it would be good to be able to constrain the aspect-ratio.  This will allow plots to fit existing report layouts without distorting text by stretching plot PNGs.  

This issue was originally part of #8.

**Comment by tomjemmett** [comment]
I think this is not an issue with R, but an issue with the excel tool being inflexible. The aspect ratio of R is determined by whatever device the plot is output too, so it's not really something we could ever control (other than providing some partial application of `ggsave()`), so I would call this out of scope! 🙂

**Comment by ThomUK** [comment]
That's fair comment.  This issue is probably more my lack of knowledge how to achieve different aspect ratios.  I'll do some research and plan to write a vignette summarising different methods:
1. Directly in rStudio
2. Using Rmd
3. Saving a file using `ggsave()`

**Comment by tomjemmett** [comment]
I've marked as wontfix, but there is a good use case for better documentation on this, and perhaps having a `ptd_save()` function with some recomended default values for width/height

**Comment by tomjemmett** [comment]
@ThomUK to write a vignette on how to output charts from R
