### ISSUE TITLE
Refactoring SPC calculations from main spc() function

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#6]
This is a sub-issue to overall issue - #2
I propose a refactoring to move the code doing the main SPC info into a separate self-contained function.  This will simplify the main function, and make the calculation code more self-contained.  

The new function will return the dataframe containing the information needed for next steps.

**Comment by chrisreading01** [comment]
I'm going to open a PR to start looking at this issue, following Tom's progress on the first subfunction. :)
