### ISSUE TITLE
Update vignette and to S3

### ISSUE THREAD

**Issue by chrismainey** [nhs-r-community/NHSRplotthedots#65]
Need to update the readme and the vignette

**Comment by chrismainey** [comment]
Add use example of `plot` and `summary`

- [ ] Add use example of `plot` and `summary`
- [ ] Add use example of `plot` and `summary`
- [ ] Remove reference to `spcOptions` directly
- [ ] Reflect changes in README.

**Comment by tomjemmett** [comment]
just a thought - if we implement #62 (moving to tidyeval) this will affect this may be implemented... I can either implement this straight after #70 , or I can implement #62 and update documentation as part of it
