### ISSUE TITLE
Check use of colour and legend

### ISSUE THREAD

**Issue by chrismainey** [nhs-r-community/NHSRplotthedots#71]
Unsure of colour use, as currently in vignette a run of 7 points on one side of the mean is called 'special cause improvement' and is colour blue.  Shouldn't this just be for outside control limits, should it be a different colour for runs of points?  Don't know the PTD rules here, so requesting some guidance from those who do.

**Comment by tomjemmett** [comment]
I'm pretty certain this is correct, as they are pretty strongly opinionated about use of colours in the plots and avoiding rag rating, but I'm not super familiar with PTD rules. Going to defer this to others!

**Comment by SimonW-M** [comment]
They definitely avoid RAG and use blue for 'good' and orange for 'bad'.   The icons work purely on comparison to process limits to identify special cause.  Runs on one side of the mean are trends and not special cause.  I did get them to confirm their methodology.  May be easier to discuss if you want a chat.

**Comment by ThomUK** [comment]
This is correct. Anything of special cause (a run one side of the mean, a trend, 2 in 3 beyond 2sigma, and a point outside limits) gets the colour. Blue if in improving direction, amber if not.

**Comment by SimonW-M** [comment]
Variation is based on latest data point being inside control for ccv or outside for special.  
Assurance is based on target being between control or above or below control.

**Comment by SimonW-M** [comment]
That was Icon rules

**Comment by SimonW-M** [comment]
Just to confirm they use the same colours for special cause as well as for runs.

**Comment by chrismainey** [comment]
Thanks all. Happy to close, but does orange need to be a 'bit more orange'?

**Comment by chrisreading01** [comment]
I feel like I did hex match them when I set the colours in the original code, but I have slept since then so worth double checking :)

**Comment by chrismainey** [comment]
Fair play. Might just be my screen too (or my eyes). It's definitely clear,
just didn't seem very orange when everyone described orange above.
