### ISSUE TITLE
Current plot output is visually different to the excel tool's output

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#8]
NHSR plotthedots output:
![image](https://user-images.githubusercontent.com/10871342/113341799-876be400-9325-11eb-8e80-7466c99099aa.png)

NHSEI excel tool output (same data):
![image](https://user-images.githubusercontent.com/10871342/113343210-6d330580-9327-11eb-94b8-a6874eb0f4ff.png)

I'd propose that by default the NHSR tool should output plots quite close in appearance to the excel tool.  The user could then choose to over-ride elements of the default theme by passing a theme over-ride object into the main spc() function (in the options list()).  

To get the NHSR output to more closely match the excel output I'd propose:
* [x] Left-aligning the title
* [ ] Making the image aspect-ratio similar
* [x] Removing vertical gridlines
* [x] ~~Removing minor horizontal gridlines~~ Tried, and looks better with minor gridlines.
* [x] Making the geom_points bigger by default
* [x] Removing default x and y axis labels ("Date" and "Value")(These can already be over-ridden with different text if needed)
* [x] ~~Rounding the y axis limits up so that they include the next major horizontal gridline out from the UPL and LPL~~ Tried this, and quite a lot of effort to achieve reliably.  For now the user can override limits with the option to pass in plot overrides.  
* [ ] Adding a legend along the bottom edge
* [x] ~~Possibly moving the x axis labels to sit just inside the plot area, to make maximum space for data~~ Tried, and looks better without doing this.
* [x] The R plot puts the mean line in the correct place, but excel tool puts it at 0.  I'm not sure why.  Perhaps rounded to an integer?  I'd propose keeping the R code, but lets talk about it.  
* [x] Adding the facility to pass in a theme over-ride for minor customisations (eg. adding or moving subtitles, captions, etc)
That list would probably get the output "close enough" for my uses.  
How does that sound?

**Comment by tomjemmett** [comment]
as #50 is now merged, is this issue resolved?
