### ISSUE TITLE
Check and reinstate missing or broken package tests

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#86]
At one time we had tests for all of the public API, to check behavior is as expected.  The original tests would have caught #85, so I think we need to check that tests are doing what we expect.

**Comment by ThomUK** [comment]
@tomjemmett I'm not sure what you think about this.  
I've not used stubs and mocks much, and have always tried to test the public API directly from the "outside" in the tests.  Having just gone through the tests I understand stubs and mocks a *little* better, but I'll defer to your judgement on this issue if you think public API tests are overkill or not helpful here.

**Comment by ThomUK** [comment]
Got you, thanks Tom. Yes, in that case I'm talking about integration tests. I agree, snapshots based on the visual plot output might be too brittle to be helpful. Looking at the plot object to check axes, labels, etc might be a good middle ground.

**Comment by tomjemmett** [comment]
I think I have some idea of how to get these tests working now, but it's requires testthat >= 3.1.0 (see [changelog](https://testthat.r-lib.org/news/index.html#snapshot-tests), 2nd point about variant argument)

**Comment by tomjemmett** [comment]
I couldn't find a reliable way of rendering plots and testing the outputs... the closest was with svg's, but these failed between different OS's...
