### ISSUE TITLE
Enable use of "rebase" and "fix_after_n_points" arguments at the same time

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#93]
[ptd_spc_options()](https://github.com/nhs-r-community/NHSRplotthedots/blob/83c4565e6bd4a437a9b747a1bb40b64e86a8dbb1/R/ptd_spc_options.R#L83) currently includes the section below, which prevents rebasing and fixing a baseline at the same time.  

```r
# TODO: check that this is correct
  assertthat::assert_that(
    is.null(fix_after_n_points) || is.null(rebase),
    msg = "cannot rebase and fix_after_n_points"
  )
```

Ideally it would be possible to use both these arguments in the same plot.  
The rebase argument would have priority, and would section the plot up into rebase groups.  SPC calcs would then apply to each group, and if any group had more than fix_after_n_points data points, the SPC calcs would ignore the excess points.  

Describing a hypothetical plot with 40 data points, a rebase at the middle date, and fix_after_n = 12, we would get:
12 points used to calculate initial limits,
8 more points plotted over the original limit lines, but not used for any limit calcs,
12 more points, which are used to calculate the rebased limits and mean,
8 final points plotted over the new limit lines, but again not used for any limit calculations

A hypothetical plot with 40 data points, a rebase after 30 points, and fix_after_n = 12, would result in:
12 points used to calculate initial limits,
28 more points plotted over the original limit lines, but not used for any limit calcs,
10 final points, all of which are used to calculate the rebased limits.

**Comment by tomjemmett** [comment]
All yours! I've assigned you. I've marked for 0.2.0 as I think that this isn't a deal breaker for 0.1.0, so gives us some time for slippage if we want to get this out sooner rather than later.

**Comment by Lextuga007** [comment]
Checking the warning on <12 points and the recommendation here https://www.england.nhs.uk/improvement-hub/wp-content/uploads/sites/44/2017/11/A-guide-to-creating-and-interpreting-run-and-control-charts.pdf is for < 10 points to use Run or X charts. Does this package include either of those?
